---
- name: configure_suricata | configuring suricata service
  template:
    src: "etc/default/suricata.j2"
    dest: "/etc/default/suricata"
    owner: root
    group: root
    mode: 0644

- name: configure_suricata | suricata_rules.yaml
  template:
    src: "etc/suricata/suricata_rules.yaml.j2"
    dest: "/etc/suricata/suricata_rules.yaml"
    owner: root
    group: root
    mode: 0644

- name: configure_suricata | suricata_outputs.yaml
  template:
    src: "etc/suricata/suricata_outputs.yaml.j2"
    dest: "/etc/suricata/suricata_outputs.yaml"
    owner: root
    group: root
    mode: 0644

- name: configure_suricata | update.yaml
  template:
    src: "etc/suricata/update.yaml.j2"
    dest: "/etc/suricata/update.yaml"
    owner: root
    group: root
    mode: 0644

- name: configure_suricata | suricata.yaml
  template:
    src: "etc/suricata/suricata.yaml.j2"
    dest: "{{ suricata_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: configure_suricata | configuring suricata suppression list
  template:
    src: "etc/suricata/threshold.config.j2"
    dest: "/etc/suricata/threshold.config"
    owner: "root"
    group: "root"
    mode: 0644

- name: remove rules for disabled protocols
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/suricata/rules/dnp3-events.rules
    - /etc/suricata/rules/modbus-events.rules

- name: start suricata
  service:
    name: suricata
    state: started

- name: run suricata-update
  become: true
  shell: suricata-update
  notify: restart suricata
