---
- name: configure_suricata | configuring suricata service
  template:
    src: "etc/default/suricata.j2"
    dest: "/etc/default/suricata"
    owner: root
    group: root
    mode: 0644
  notify: restart suricata

- name: configure_suricata | configuring suricata
  template:
    src: "etc/suricata/suricata.yaml.j2"
    dest: "{{ suricata_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart suricata

- name: configure_suricata | configuring suricata suppression list
  template:
    src: "etc/suricata/threshold.config.j2"
    dest: "/etc/suricata/threshold.config"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart suricata

- name: remove rules for disabled protocols
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/suricata/rules/dnp3-events.rules
    - /etc/suricata/rules/modbus-events.rules

- name: run suricata-update
  become: true
  shell: suricata-update
